import type { Metadata } from 'next'
import "../components/globals.css"
import Image from 'next/image'
import Link from 'next/link'
import { AppBar, Toolbar, Box, Stack, Button, Typography } from '@mui/material'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-Br">
      <body >
        <AppBar className='relative bg-gray-100' position="relative">
          <Toolbar className='justify-center'>
            <Image alt='teste' src='/home/logo1.svg' height="300" width="300" />
          </Toolbar>
          <Box className='justify-center flex'>
            <Stack className='flex-row justify-between w-9/12'>
              <Link href=''>
                <Button>Home</Button>
              </Link>
              <Link href=''>
                <Button>Galeria</Button>
              </Link>
              <Link href=''>
                <Button>Eventos</Button>
              </Link>
              <Link href=''>
                <Button>Contato</Button>
              </Link>
            </Stack>
          </Box>
        </AppBar>
        {children}
        <div className='bg-gray-800 w-full'>
          <div className=' justify-center flex'>
            <div className='w-9/12  flex gap-10 justify-center'>
              <button>
                <p className="text-white text-2xl">
                  Instagram
                </p>
              </button>
              <Link href="https://wa.me/5548991220902?text=Ol%C3%A1%2C+vim+pelo+site%21">
                <button>
                  <p className="text-white text-2xl">
                    WhatsApp
                  </p>
                </button>
              </Link>
            </div>
          </div>
          <Typography className='p-5 text-white text-center'>
            Todos os direitos reservados. ®
          </Typography>
        </div>
      </body>
    </html>
  )
}